# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 716d628640291a2b79bf48ebd6666e8cc97e1ebc78ca72c427bcd8ebb767e9162f79627e9955c42044e75742cb1a8c4c0454fadada49268a3cb6f28bf2baf7f8

test:
  secret_key_base: e07406133db729915236cd1baca2d5bb4d6cde6c586981a31c51de28eb7163a906d6f0f052ec266ac5392eadce039f2b655b4ecd696db0eaa2e361c559f64844

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
